version: '1'

services:
  frontend:
    build:
      context: ./web-frontend
      dockerfile: ./web-frontend/Dockerfile
    container_name: web-frontend
    ports:
      - "5000:5000" 

  backend:
    build:
      context: ./web-backend
      dockerfile: ./web-frontend/Dockerfile
    container_name: web-backend
    ports:
      - "8080:8080" 

  database:
    image: postgres:14
    container_name: web-database
    environment:
      POSTGRES_DB: clinica_db       # Default database to create
      POSTGRES_USER: clinica_user   # Default user
      POSTGRES_PASSWORD: 1234       # Default user's password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data between container restarts



